AWSTemplateFormatVersion: 2010-09-09
Description: Create Database Migration Service Replication Instance
  Instances.
Metadata:
  LICENSE: Apache License Version 2.0
  'AWS::CloudFormation::Interface':
    ParameterGroups:
      - Label:
          default: DMS Replication Instance Configuration
        Parameters:
          - CreateNewReplicationInstance
          - ReplInstanceArn
          - Subnets
          - SecurityGroup
          - InstanceType
          - EngineVersion
          - PublicAccess
          - MultiAz
      - Label:
          default: Source Database Configuration
        Parameters:
          - SourceDBName
          - SourceEngine
          - SourcePassword
          - SourcePort
          - SourceEndpointServer
          - SourceUser
      - Label:
          default: Target Database Configuration
        Parameters:
          - TargetDBName
          - TargetEngine
          - TargetPassword
          - TargetPort
          - TargetEndpointServer
          - TargetUser
      - Label:
          default: Lambda Layer Configuration
        Parameters:
          - LayerBucket
          - LayerKey
    ParameterLabels:
      CreateNewReplicationInstance:
        default: Create New Replication Instance?
      ReplInstanceArn:
        default: Existing DMS Replication Instance Arn
      LayerBucket:
        default: Layer S3 Bucket
      LayerKey:
        default: Layer S3 Key
      SourceDBName:
        default: Source Database Name
      SourceEngine:
        default: Source Database Engine
      SourcePassword:
        default: Source Database Password
      SourcePort:
        default: Source Database Port
      SourceEndpointServer:
        default: Source Database Endpoint
      SourceUser:
        default: Source Database Username
      TargetDBName:
        default: Target Database Name
      TargetEngine:
        default: Target Database Engine
      TargetPassword:
        default: Target Database Password
      TargetPort:
        default: Target Database Port
      TargetEndpointServer:
        default: Target Database Endpoint
      TargetUser:
        default: Target Database Username
      EngineVersion:
        default: Replication Engine Version
      InstanceType:
        default: Instance Type
      MultiAz:
        default: Enable MultiAZ
      PublicAccess:
        default: Allow Public Access
      SecurityGroup:
        default: Security Group
      Subnets:
        default: Subnet IDs
Parameters:
  CreateNewReplicationInstance:
    Type: String
    AllowedValues:
      - 'yes'
      - 'no'
    Description: Please specify if you want to create new replication instance
  ReplInstanceArn:
    Type: String
    Description: Arn of the DMS replication instance
  EngineVersion:
    AllowedValues:
      - 3.1.3
      - 2.4.5
      - 2.4.4
      - 2.4.3
    Default: 3.1.3
    Description: DMS replication engine version
    Type: String
  InstanceType:
    AllowedValues:
      - dms.t2.micro
      - dms.t2.small
      - dms.t2.medium
      - dms.t2.large
      - dms.c4.large
      - dms.c4.xlarge
      - dms.c4.2xlarge
      - dms.c4.4xlarge
    Default: dms.t2.micro
    Description: DMS replication instance type
    Type: String
  MultiAz:
    AllowedValues:
      - 'true'
      - 'false'
    Default: 'false'
    Description: Enable MultiAZ
    Type: String
  PublicAccess:
    AllowedValues:
      - 'true'
      - 'false'
    Default: 'false'
    Description: Publicly Accessible
    Type: String
  SecurityGroup:
    Description: 'Security group ID for DMS replication instance (e.g., sg-1234abcd)'
    Type: 'AWS::EC2::SecurityGroup::Id'
  Subnets:
    Description: Choose two subnets in different availability zones (e.g., subnet-1234abcd,
      subnet-abcd1234)
    Type: 'List<AWS::EC2::Subnet::Id>'
  SourceDBName:
    Type: String
    Description: Name of the database in source server
  SourceEngine:
    Type: String
    Description: Database engine running on the source
    AllowedValues:
      - mysql
      - oracle
      - postgres
      - mariadb
      - aurora
      - aurora-postgresql
      - redshift
      - db2
      - azuredb
      - sybase
      - sqlserver
  SourcePassword:
    Type: String
    Description: Source database password
    NoEcho: 'true'
  SourcePort:
    Type: String
    Description: Port on which the source database is running
  SourceEndpointServer:
    Type: String
    Description: Source database hostname, endpoint URL or IP address
  SourceUser:
    Type: String
    Description: Source database user name
  TargetDBName:
    Type: String
    Description: Name of the database in target server
  TargetEngine:
    Type: String
    Description: Database engine running on the target
    AllowedValues:
      - mysql
      - oracle
      - postgres
      - mariadb
      - aurora
      - aurora-postgresql
      - redshift
      - db2
      - azuredb
      - sybase
      - sqlserver
  TargetPassword:
    Type: String
    Description: Target database password
    NoEcho: 'true'
  TargetPort:
    Type: String
    Description: Port on which the target database is running
  TargetEndpointServer:
    Type: String
    Description: Target database hostname, endpoint URL or IP address
  TargetUser:
    Type: String
    Description: Target database user name
  LayerBucket:
    Type: String
    Description: S3 bucket of the packaged zip file eampole (test-bucket-1234)
  LayerKey:
    Type: String
    Description: S3 location of the packaged zip file example (folder/sub-folder/test.zip)
Conditions:
  CreateReplicationInstance: !Equals
    - !Ref CreateNewReplicationInstance
    - 'yes'

Resources:
  ReplicationInstance:
    Condition: CreateReplicationInstance
    Properties:
      EngineVersion: !Ref EngineVersion
      MultiAZ: !Ref MultiAz
      PubliclyAccessible: !Ref PublicAccess
      ReplicationInstanceClass: !Ref InstanceType
      ReplicationSubnetGroupIdentifier: !Ref ReplicationSubnetGroup
      Tags:
        - Key: Name
          Value: !Sub '${AWS::StackName}-ReplicationSetup'
        - Key: Product
          Value: DMS-Automation-ReplicationSetup
        - Key: Solution
          Value: DMS-Automation-ReplicationSetup
      VpcSecurityGroupIds:
        - !Ref SecurityGroup
    Type: 'AWS::DMS::ReplicationInstance'
  SourceEndpoint:
    Type: 'AWS::DMS::Endpoint'
    Properties:
      DatabaseName: !Ref SourceDBName
      EndpointType: source
      EngineName: !Ref SourceEngine
      Password: !Ref SourcePassword
      Port: !Ref SourcePort
      ServerName: !Ref SourceEndpointServer
      Tags:
        - Key: Name
          Value: !Sub '${AWS::StackName}-ReplicationSetup'
        - Key: Product
          Value: DMS-Automation-ReplicationSetup
        - Key: Solution
          Value: DMS-Automation-ReplicationSetup
      Username: !Ref SourceUser
  TargetEndpoint:
    Type: 'AWS::DMS::Endpoint'
    Properties:
      DatabaseName: !Ref TargetDBName
      EndpointType: target
      EngineName: !Ref TargetEngine
      Password: !Ref TargetPassword
      Port: !Ref TargetPort
      ServerName: !Ref TargetEndpointServer
      Tags:
        - Key: Name
          Value: !Sub '${AWS::StackName}-ReplicationSetup'
        - Key: Product
          Value: DMS-Automation-ReplicationSetup
        - Key: Solution
          Value: DMS-Automation-ReplicationSetup
      Username: !Ref TargetUser
  ReplicationSubnetGroup:
    Condition: CreateReplicationInstance
    Properties:
      ReplicationSubnetGroupDescription: DMS Automation Subnets
      SubnetIds: !Ref Subnets
      Tags:
        - Key: Name
          Value: !Sub '${AWS::StackName}-ReplicationSetup'
        - Key: Product
          Value: DMS-Automation-ReplicationSetup
        - Key: Solution
          Value: DMS-Automation-ReplicationSetup
    Type: 'AWS::DMS::ReplicationSubnetGroup'
  CheckEndpointConnection:
    Type: 'Custom::DmsEndpointConnectionTester'
    Properties:
      ServiceToken: !GetAtt
        - DmsEndpointConnTest
        - Arn
      SourceArn: !Ref SourceEndpoint
      TargetArn: !Ref TargetEndpoint
      ReplicationInstanceArn: !If [CreateReplicationInstance, !Ref ReplicationInstance, !Ref ReplInstanceArn]
  DmsEndpointConnTestRole:
    Type: 'AWS::IAM::Role'
    Properties:
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Principal:
              Service: lambda.amazonaws.com
            Action: 'sts:AssumeRole'
      ManagedPolicyArns:
        - 'arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole'
      Path: /
      Policies:
        - PolicyName: dms-connection-access
          PolicyDocument:
            Version: 2012-10-17
            Statement:
              - Effect: Allow
                Action:
                  - 'dms:DescribeConnections'
                  - 'dms:TestConnection'
                Resource: '*'
  DmsEndpointConnTestLayer:
    Type: 'AWS::Lambda::LayerVersion'
    Properties:
      CompatibleRuntimes:
        - python3.6
        - python3.7
      Content:
        S3Bucket: !Ref LayerBucket
        S3Key: !Ref LayerKey
      Description: Latest boto3 layer for DMS wait handler
  DmsEndpointConnTest:
    Type: 'AWS::Lambda::Function'
    Properties:
      Description: Checks the connection between DMS replication instance and DMS endpoint
      Handler: index.lambda_handler
      Runtime: python3.6
      Role: !GetAtt
        - DmsEndpointConnTestRole
        - Arn
      Timeout: 900
      Layers:
        - !Ref DmsEndpointConnTestLayer
      Code:
        ZipFile: |
          import cfnresponse
          import json
          import boto3

          def lambda_handler(event, context):
              source_endpoint = event['ResourceProperties']['SourceArn']
              target_endpoint = event['ResourceProperties']['TargetArn']
              replication_inst = event['ResourceProperties']['ReplicationInstanceArn']
              if 'Create' or 'Update' in event['RequestType']:
                  print ('This is a %s event' %(event['RequestType']))
                  print('Checking connection for Source .....')
                  source_result = check_connection(source_endpoint,replication_inst)
                  print('Source result was %s' %(source_result))
                  if 'success' in source_result:
                      print('Proceeding to check connection for Target ....')
                      target_result = check_connection(target_endpoint,replication_inst)
                      print('Target result was %s' %(target_result))
                      if 'success' in target_result:
                          cfnresponse.send(event, context, cfnresponse.SUCCESS, {}, '')
                      else:
                          print('Target connection failed')
                          cfnresponse.send(event, context, cfnresponse.FAILED, {}, '')
                  else:
                      print('Source connection failed')
                      cfnresponse.send(event, context, cfnresponse.FAILED, {}, '')
              else:
                  print('Delete event nothing will be done')
                  cfnresponse.send(event, context, cfnresponse.FAILED, {}, '')
          def check_connection(endpoint,rep):
              dms = boto3.client('dms')
              dms.test_connection(ReplicationInstanceArn=rep,EndpointArn=endpoint)
              waiter = dms.get_waiter('test_connection_succeeds')
              waiter.wait(
                  Filters=[
                      {
                          'Name': 'endpoint-arn',
                          'Values': [endpoint]
                      },
                      {
                          'Name': 'replication-instance-arn',
                          'Values':[rep]
                      }
                  ]
              )
              status_conn_api = dms.describe_connections(
                  Filters=[
                      {
                          'Name': 'endpoint-arn',
                          'Values': [endpoint]
                      },
                      {
                          'Name': 'replication-instance-arn',
                          'Values': [rep]
                      }
                  ]
              )
              stat_task = status_conn_api['Connections'][0]['Status']
              print('The connection test was %s' %(stat_task))
              return (stat_task)
Outputs:
  SourceEndpointArn:
    Description: DMS Source Endpoint Arn
    Value: !Ref SourceEndpoint
  TargetEndpointArn:
    Description: DMS Target Endpoint Arn
    Value: !Ref TargetEndpoint
  ReplicationInstanceArn:
    Description: DMS Replication Instance Arn
    Value: !If [CreateReplicationInstance, !Ref ReplicationInstance, !Ref ReplInstanceArn]
